service: online-library-monitor

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: eu-west-1


functions:
  processor:
    handler: handler.processor
    events:
      - cloudwatchLog: 
          logGroup: ${self:custom.logGroup}
          filter: '?ERROR ?Exception'


# custom variables
custom:
  logGroup: /aws/lambda/online-library-dev-main
  


