service: bookcategory-upload

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DB_NAME: ${self:custom.DB_NAME.dev}
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:eu-west-1:<accountId>:table/online-library


functions:
  bookCategoryS3EventProcessor:
    name: bookCategoryImporter
    handler: handler.processor
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

custom:
  bucket: bookcategories
  stages:
    - dev
  DB_NAME:
    dev: online-library

